id: P006784
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:22:44.621302
source_metadata:
  id: bdr:W22126
  title: རྒྱ་ནག་རྟོགས་ལྡན་བྱན་ཆུབ་འཕགས་དབང་གི་རྣམ་ཐར་དད་གསུམ་ཆུ་འཕེལ་བའི་ཟླ་གཟོན
  author: ''
  volumes:
    d2d067a059174213af5d83ab1d593c0d:
      image_group_id: I2800
      title: ''
      volume_number: 1
      total_pages: 335
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
