id: IB486D44D
legacy_id: P006784
ocr_import_info:
  bdrc_scan_id: W22126
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T20:57:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:44:23.813843+00:00'
last_modified: 2022-09-02 04:44:28.108421
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22126
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22126
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: rgya nag rtogs ldan byan chub 'phags dbang gi rnam thar dad gsum chu 'phel
    ba'i zla gzon
  author: རྒྱ་ནག་རྟོགས་ལྡན ༠༢་ངག་དབང་བློ་གྲོས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9743243332381721
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2800:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2800
      total_pages: 335
      volume_number: 1
      volume_pages_bdrc_intro: 1
    order: 1
    base_file: I2800.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9743243332381721
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
