id: IB486D44D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T20:57:15+00:00'
last_modified: '2022-06-08T06:50:07.080330+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22126
  title: རྒྱ་ནག་རྟོགས་ལྡན་བྱན་ཆུབ་འཕགས་དབང་གི་རྣམ་ཐར་དད་གསུམ་ཆུ་འཕེལ་བའི་ཟླ་གཟོན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1112':
      image_group_id: I2800
      title: ''
      total_pages: 335
      order: 1
      base_file: 1112.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
